"""
The price table, and the guard that stops Gutty inventing one.

`facts/prices.yaml` is generated by `scripts/pull_products.py` from Zoho
Products. This module reads it and answers two questions: what may be quoted,
and whether an amount in a composed reply is real.

**Why a guard and not a prompt instruction.** The system prompt already says
"nunca inventes precios". That is a request. On 2026-08-11 both policy surfaces
were quoting a $229 plan Zoho had marked inactive, and the retrieval corpus was
quoting it too — so the model would have been *grounded* in the wrong number and
said it with confidence. A number a patient is told is a number the business has
to honour, so it gets checked rather than requested.
"""
from __future__ import annotations

import functools
import logging
import os
import re
from decimal import Decimal
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

# "$249", "$1,690", "$49.99", "249 USD"
AMOUNT = re.compile(r"\$\s?(\d[\d.,]*)|(?<![\d.,])(\d[\d.,]*)\s?(?:USD|usd)")


def _candidate_paths() -> list[Path]:
    """
    Where the generated table might be.

    Installed, this module lives in site-packages and the repo root is nowhere
    above it — walking up from `__file__` lands in the Python install. The image
    puts the table at /app/facts, which is the working directory, so the CWD
    candidate is the one that resolves in production.
    """
    override = os.environ.get("NW_PRICES_PATH")
    if override:
        return [Path(override)]
    return [
        Path.cwd() / "facts" / "prices.yaml",
        # Development, running from anywhere inside the repo checkout.
        Path(__file__).resolve().parents[4] / "facts" / "prices.yaml",
    ]


@functools.lru_cache(maxsize=1)
def catalogue() -> dict:
    """
    The generated table.

    A missing table is **not** treated as "no prices to check". Every amount
    then reads as unverified and priced answers escalate to a human — degraded,
    but never quoting a number nobody set. The alternative, waving amounts
    through when the table cannot be loaded, would reproduce the exact failure
    this guard exists for on the day a build drops the file.
    """
    for path in _candidate_paths():
        if path.is_file():
            loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
            if loaded and loaded.get("products"):
                return loaded
    logger.error(
        "price table not found (looked in %s) — every priced reply will be escalated. "
        "Run scripts/pull_products.py.",
        [str(p) for p in _candidate_paths()],
    )
    return {"families": {}, "products": {}}


def quotable_plans() -> list[dict]:
    """Non-F&F plans in a family a patient may be offered, cheapest first."""
    products = catalogue().get("products") or {}
    plans = [p for p in products.values() if p.get("quotable")]
    return sorted(plans, key=lambda p: (str(p.get("family")), p.get("consultations") or 0))


def known_amounts() -> set[Decimal]:
    """Every active product price. Exams and courses count: they are real prices."""
    products = catalogue().get("products") or {}
    amounts: set[Decimal] = set()
    for product in products.values():
        price = product.get("price_usd")
        if price is not None:
            amounts.add(Decimal(str(price)))
    return amounts


def _to_decimal(raw: str) -> Decimal | None:
    """
    Parse a written amount. '1,690' is one thousand six hundred and ninety;
    '49.99' is not. Spanish and English both appear in this corpus, so a comma
    is treated as a thousands separator only when it is not the decimal point.
    """
    text = raw.strip().rstrip(".,")
    if not text:
        return None
    if "," in text and "." in text:
        text = text.replace(",", "")
    elif "," in text:
        # A single comma with exactly two digits after it is a decimal comma.
        head, _, tail = text.rpartition(",")
        text = f"{head}.{tail}" if len(tail) == 2 else text.replace(",", "")
    try:
        return Decimal(text)
    except Exception:  # noqa: BLE001 - unparseable is "not a price we can vouch for"
        return None


def amounts_in(text: str) -> set[Decimal]:
    """Every dollar amount a piece of text asserts."""
    found: set[Decimal] = set()
    for match in AMOUNT.finditer(text or ""):
        value = _to_decimal(match.group(1) or match.group(2) or "")
        if value is not None:
            found.add(value)
    return found


def unverified_amounts(reply: str, *, grounding: str = "") -> set[Decimal]:
    """
    Amounts in `reply` that neither the price table nor the grounding supports.

    Grounding counts because a patient may ask about an exam or a course whose
    price lives in the knowledge corpus rather than in the plan catalogue. What
    must not happen is an amount that appears in neither — that is the model
    doing arithmetic, or remembering, and both are how a retired price survives.
    """
    return amounts_in(reply) - known_amounts() - amounts_in(grounding)
